import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <nav className="bg-slate-100 flex">
          <a className="bg-slate-300 p-3 m-2 rounded-xl" href="/">
            <Image src="/favicon.ico" width={32} height={32} alt="logo" />
          </a>
          <ul className="flex">
            <a href="about" className="bg-slate-300 p-3 m-2 rounded-xl">
              <li className="">About</li>
            </a>
            <a href="sign-up" className="bg-slate-300 p-3 m-2 rounded-xl">
              <li className="">Sign Up</li>
            </a>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
